### ISSUE TITLE
setup lens (decentral social media)

### ISSUE THREAD

**Issue by normadn** [frens-pool/frens#5]

**Comment by dameos** [comment]
@normadn I am bit confused by this. 
Should I try to set up a lens profile for frens? or is it more about as a frens user being able to see your lens's profile information in the frens app?

**Comment by normadn** [comment]
It's about getting a lens handle for frens in the first place ... but tbh maybe I need to ask them since it is invite only currently

**Comment by normadn** [comment]
done by @heeckhau
